from .chatterbox_node import NODE_CLASS_MAPPINGS as CHATTERBOX_NODE_CLASS_MAPPINGS
from .chatterbox_node import NODE_DISPLAY_NAME_MAPPINGS as CHATTERBOX_NODE_DISPLAY_NAME_MAPPINGS
from .chatterbox_dialog_node import NODE_CLASS_MAPPINGS as DIALOG_NODE_CLASS_MAPPINGS
from .chatterbox_dialog_node import NODE_DISPLAY_NAME_MAPPINGS as DIALOG_NODE_DISPLAY_NAME_MAPPINGS

# Combine all node mappings
NODE_CLASS_MAPPINGS = {}
NODE_CLASS_MAPPINGS.update(CHATTERBOX_NODE_CLASS_MAPPINGS)
NODE_CLASS_MAPPINGS.update(DIALOG_NODE_CLASS_MAPPINGS)

NODE_DISPLAY_NAME_MAPPINGS = {}
NODE_DISPLAY_NAME_MAPPINGS.update(CHATTERBOX_NODE_DISPLAY_NAME_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(DIALOG_NODE_DISPLAY_NAME_MAPPINGS)

# Update display names to indicate Intel Arc compatibility
NODE_DISPLAY_NAME_MAPPINGS["FL_ChatterboxTTS"] = "FL Chatterbox TTS (Intel Arc)"
NODE_DISPLAY_NAME_MAPPINGS["FL_ChatterboxVC"] = "FL Chatterbox VC (Intel Arc)" 
NODE_DISPLAY_NAME_MAPPINGS["FL_ChatterboxDialogTTS"] = "FL Chatterbox Dialog TTS (Intel Arc)"

__all__ = ['NODE_CLASS_MAPPINGS', 'NODE_DISPLAY_NAME_MAPPINGS']
